### ISSUE TITLE
排版和一些符號的呈現方式

### ISSUE THREAD

**Issue by junsuwhy** [felixshai/open-source-guide#8]
我看前面的翻譯情況，想說有些翻法要不要訂下來，
目前看到是這幾個：

1. [中英文之間加空格](https://github.com/felixshai/open-source-guide/commit/30ba8a31e3d4ed94d094603fc8c295ebc5547f1d#diff-c9b156787289d7c26178b68886e8b583R239)
2. ["" 這個引號改成 「」](https://github.com/felixshai/open-source-guide/commit/8dbc6e39dc002c3647305854bb72af7b332a11f9#diff-4671f2bf97d1d254ebb89c1055c02cecR48)
3. [(...) 在簡中被翻譯成 （。。。），但應該保留 (...)](https://github.com/felixshai/open-source-guide/commit/8dbc6e39dc002c3647305854bb72af7b332a11f9#diff-4671f2bf97d1d254ebb89c1055c02cecR42)

其他有什麼特殊的表現方式看要不要也記下來。

**Comment by junsuwhy** [comment]
4. [h2(##) 和 h3(###) 有加上粗體 ](https://github.com/felixshai/open-source-guide/commit/d70d08dd8e20ea1a8e431125ae5d65ccf2303199#diff-c9b156787289d7c26178b68886e8b583R17)

**Comment by felixshai** [comment]
這個之前有想到說要做個規範說明，歡迎繼續提出翻譯規則，我這幾天會整理好放在 README.md 上

**Comment by felixshai** [comment]
|規則名稱|翻譯方式|
|:-|:-|
|引號轉換 quotation change|原作中引句使用雙引號`""`部分改為`「」`|
|小括號轉全形 fullwidth parentheses|原作中`()` 換成 `（）`，使用新注音可透過按 \` 後 `shift`+`(` 輸入全形小括號|
|大小標轉粗體 Bold the title|因為字的格式相同，導致標題與內文視覺上分不出來，所以需要將大小標轉為粗體|
|中英文之間加空格 whitespace between languages|為使排版易讀，中英文字之間需用半形空格格開|
|引文省略時表達方式|簡中使用（。。。）但應該保留(...)|

**Comment by felixshai** [comment]
已在 README.MD 中加入翻譯規則
